
DELETE FROM "AnimalSpecies";
TRUNCATE TABLE "AnimalSpecies" RESTART IDENTITY CASCADE;


DELETE FROM "AnimalBreed";
TRUNCATE TABLE "AnimalBreed" RESTART IDENTITY CASCADE;


DELETE FROM "Animal";
TRUNCATE TABLE "Animal" RESTART IDENTITY CASCADE;


DELETE FROM "Agreement";
TRUNCATE TABLE "Agreement" RESTART IDENTITY CASCADE;


DELETE FROM "PawLog";
TRUNCATE TABLE "PawLog" RESTART IDENTITY CASCADE;