export const ENV = {
    NODE_ENV: process.env.NODE_ENV,
    API_URL: process.env.NEXT_PUBLIC_API_URL,
    AZURE_STORAGE_DOMAIN: process.env.NEXT_PUBLIC_AZURE_STORAGE_DOMAIN,
    AZURE_PUBLIC_CONTAINER: process.env.NEXT_PUBLIC_AZURE_PUBLIC_CONTAINER,
    
} as const;

